import { describe, expect, it } from 'vitest';
import { applyPdmEdits } from './xmlPatch';

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner signature="PDM_DATA_MODEL_XML" version="16.6"?>
<!-- do not edit this file -->
<Model>
<c:Tables>
<o:Table Id="o9">
<a:Name>Table_1</a:Name>
<a:Code>Table_1</a:Code>
<c:Columns>
<o:Column Id="o12">
<a:Name>Column_1</a:Name>
<a:Code>Column_1</a:Code>
<a:DataType>INT8</a:DataType>
<a:Length>8</a:Length>
<a:Column.Mandatory>1</a:Column.Mandatory>
</o:Column>
<o:Column Id="o13">
<a:Name>Column_2</a:Name>
<a:Code>Column_2</a:Code>
<a:DataType>FLOAT8</a:DataType>
</o:Column>
</c:Columns>
<c:Keys>
<o:Key Id="o14">
<c:Key.Columns>
<o:Column Ref="o12"/>
</c:Key.Columns>
</o:Key>
</c:Keys>
</o:Table>
</c:Tables>
</Model>`;

describe('applyPdmEdits', () => {
  it('reemplaza un atributo existente', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Table', pdId: 'o9', child: 'a:Name', value: 'Clientes' },
    ]);
    expect(result).toContain('<a:Name>Clientes</a:Name>');
    expect(result).toContain('<a:Code>Table_1</a:Code>');
  });

  it('inserta un atributo ausente antes del cierre', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Table', pdId: 'o9', child: 'a:Comment', value: 'Tabla de clientes' },
    ]);
    expect(result).toContain('<a:Comment>Tabla de clientes</a:Comment>');
    expect(result.indexOf('<a:Comment>')).toBeLessThan(result.indexOf('</o:Table>'));
    expect(result.indexOf('<a:Comment>')).toBeGreaterThan(result.indexOf('<a:Code>'));
  });

  it('elimina el atributo cuando el valor es null', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Column', pdId: 'o12', child: 'a:Column.Mandatory', value: null },
    ]);
    expect(result).not.toContain('Column.Mandatory');
    expect(result).toContain('<a:Length>8</a:Length>');
  });

  it('marca NOT NULL con el valor 1', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Column', pdId: 'o13', child: 'a:Column.Mandatory', value: true },
    ]);
    expect(result).toContain('<a:Column.Mandatory>1</a:Column.Mandatory>');
    expect(result.match(/<a:Column\.Mandatory>/g)).toHaveLength(2);
  });

  it('no toca otras columnas con el mismo atributo', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Column', pdId: 'o13', child: 'a:Name', value: 'Importe' },
    ]);
    expect(result).toContain('<a:Name>Importe</a:Name>');
    expect(result).toContain('<a:Name>Column_1</a:Name>');
    expect(result).not.toContain('<a:Name>Column_2</a:Name>');
  });

  it('ignora referencias self-closing con el mismo nombre de etiqueta', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Column', pdId: 'o12', child: 'a:Name', value: 'Id' },
    ]);
    expect(result).toContain('<o:Column Ref="o12"/>');
    expect(result).toContain('<a:Name>Id</a:Name>');
    expect(result).toContain('<a:Name>Column_2</a:Name>');
  });

  it('escapa caracteres XML en los valores', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Table', pdId: 'o9', child: 'a:Comment', value: 'A < B & C' },
    ]);
    expect(result).toContain('<a:Comment>A &lt; B &amp; C</a:Comment>');
  });

  it('escribe números sin decimales espurios', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Column', pdId: 'o12', child: 'a:Length', value: 32 },
    ]);
    expect(result).toContain('<a:Length>32</a:Length>');
  });

  it('devuelve el XML intacto si el id no existe', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Column', pdId: 'zzz', child: 'a:Name', value: 'Nope' },
    ]);
    expect(result).toBe(xml);
  });

  it('aplica varios parches de forma acumulativa', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Table', pdId: 'o9', child: 'a:Name', value: 'Clientes' },
      { element: 'o:Column', pdId: 'o12', child: 'a:Name', value: 'ID' },
      { element: 'o:Column', pdId: 'o13', child: 'a:Column.Mandatory', value: true },
      { element: 'o:Column', pdId: 'o12', child: 'a:Column.Mandatory', value: null },
    ]);
    expect(result).toContain('<a:Name>Clientes</a:Name>');
    expect(result).toContain('<a:Name>ID</a:Name>');
    expect(result.match(/<a:Column\.Mandatory>/g)).toHaveLength(1);
  });

  it('conserva la firma y el comentario de PowerDesigner', () => {
    const result = applyPdmEdits(xml, [
      { element: 'o:Table', pdId: 'o9', child: 'a:Name', value: 'Clientes' },
    ]);
    expect(result.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(result).toContain('<?PowerDesigner signature="PDM_DATA_MODEL_XML" version="16.6"?>');
    expect(result).toContain('<!-- do not edit this file -->');
  });
});
