import type { Column, Index, Model, Reference, Table } from '../model/types';

export function escapeIdentifier(name: string): string {
  const safe = String(name ?? '').replace(/"/g, '""');
  return `"${safe}"`;
}

function getColumnById(table: Table, columnId: string | undefined): Column | undefined {
  if (!columnId) return undefined;
  return table.columns.find((column) => column.id === columnId || column.code === columnId || column.name === columnId);
}

function normalizeOracleType(base: string, length?: number, precision?: number): string {
  const upper = base.trim().toUpperCase();

  // Tipos de otros motores que aparecen en los .pdm y no existen en Oracle.
  if (upper === 'INT8' || upper === 'INT4' || upper === 'INT2' || upper === 'SERIAL') {
    return length ? `NUMBER(${length})` : 'NUMBER';
  }
  if (upper === 'FLOAT8' || upper === 'FLOAT4' || upper === 'DOUBLE PRECISION' || upper === 'REAL') {
    return 'NUMBER';
  }
  if (upper === 'BOOL') return 'NUMBER(1)';
  if (upper === 'BYTEA') return 'BLOB';
  if (upper === 'TIMESTAMPTZ' || upper === 'TIMESTAMP WITH TIME ZONE') return 'TIMESTAMP';
  if (upper === 'MONEY') return 'NUMBER(16, 2)';
  if (upper === 'UNKNOWN' || upper === '') return 'VARCHAR2(255)';

  if (upper === 'INTEGER' || upper === 'INT') return 'NUMBER';
  if (upper === 'BIGINT') return 'NUMBER(19)';
  if (upper === 'SMALLINT') return 'NUMBER(5)';
  if (upper === 'VARCHAR') return length ? `VARCHAR2(${length})` : 'VARCHAR2(255)';
  if (upper === 'CHAR') return length ? `CHAR(${length})` : 'CHAR(1)';
  if (upper === 'TEXT' || upper === 'LONGTEXT' || upper === 'CLOB') return 'CLOB';
  if (upper === 'BOOLEAN') return 'NUMBER(1)';
  if (upper === 'DATE' || upper === 'DATETIME') return 'DATE';
  if (upper === 'TIMESTAMP') return 'TIMESTAMP';
  if (upper === 'DECIMAL' || upper === 'NUMERIC' || upper === 'FLOAT' || upper === 'DOUBLE') {
    if (length != null && precision != null) return `NUMBER(${length}, ${precision})`;
    if (length != null) return `NUMBER(${length})`;
    return 'NUMBER';
  }
  if (upper === 'BLOB') return 'BLOB';

  if (length != null && precision != null) return `${upper}(${length}, ${precision})`;
  if (length != null) return `${upper}(${length})`;
  return upper;
}

export function formatDataType(column: Column): string {
  return normalizeOracleType(String(column.dataType ?? 'VARCHAR'), column.length, column.precision);
}

/** Nombre de la restricción de clave primaria: la del modelo si existe. */
export function pkConstraintName(table: Pick<Table, 'name' | 'keys'>): string {
  const primary = table.keys?.find((key) => key.isPrimary);
  return primary?.name || `PK_${table.name}`;
}

export function formatDefaultValue(value: string | undefined): string | undefined {
  if (value == null) return undefined;
  const trimmed = value.trim();
  if (!trimmed) return undefined;
  if (/^\d+(\.\d+)?$/.test(trimmed) || /^TRUE|FALSE$/i.test(trimmed) || /^NULL$/i.test(trimmed)) {
    return trimmed.toUpperCase();
  }
  if (/^['\"]/.test(trimmed) || /\b(SYSDATE|CURRENT_DATE|CURRENT_TIMESTAMP|USER|SYSTIMESTAMP)\b/i.test(trimmed)) {
    return trimmed;
  }
  return `'${trimmed.replace(/'/g, "''")}'`;
}

export function generateTableSql(
  table: Pick<Table, 'name' | 'columns' | 'primaryKey' | 'indexes' | 'keys'>,
): string {
  const lines: string[] = [];
  lines.push(`CREATE TABLE ${escapeIdentifier(table.name)} (`);

  const columnLines = table.columns.map((column) => {
    const parts = [
      `  ${escapeIdentifier(column.name)}`,
      formatDataType(column),
    ];

    if (column.identity) {
      parts.push('GENERATED BY DEFAULT AS IDENTITY');
    }

    if (column.mandatory) {
      parts.push('NOT NULL');
    }

    if (column.defaultValue) {
      const defaultValue = formatDefaultValue(column.defaultValue);
      if (defaultValue) parts.push(`DEFAULT ${defaultValue}`);
    }

    return parts.join(' ');
  });

  if (table.primaryKey && table.primaryKey.length > 0) {
    const pkColumns = table.primaryKey
      .map((columnId) => getColumnById(table as Table, columnId))
      .filter((column): column is Column => Boolean(column))
      .map((column) => escapeIdentifier(column.name));

    if (pkColumns.length > 0) {
      columnLines.push(`  CONSTRAINT ${escapeIdentifier(pkConstraintName(table))} PRIMARY KEY (${pkColumns.join(', ')})`);
    }
  }

  lines.push(columnLines.join(',\n'));
  lines.push(');');

  const indexStatements = (table.indexes ?? []).map((index) => generateIndexSql(table, index));

  if (indexStatements.length > 0) {
    return `${lines.join('\n')}\n\n${indexStatements.join('\n\n')}`;
  }

  return lines.join('\n');
}

export function generateIndexSql(table: Pick<Table, 'name' | 'columns'>, index: Index): string {
  const columnNames = index.columns
    .map((columnId) => getColumnById(table as Table, columnId))
    .filter((column): column is Column => Boolean(column))
    .map((column) => escapeIdentifier(column.name));

  const prefix = index.unique ? 'UNIQUE ' : '';
  return `CREATE ${prefix}INDEX ${escapeIdentifier(index.name)} ON ${escapeIdentifier(table.name)} (${columnNames.join(', ')});`;
}

export function generateReferenceSql(reference: Reference, tablesById: Map<string, Table>): string {
  const parentTable = tablesById.get(reference.parentTable);
  const childTable = tablesById.get(reference.childTable);

  if (!parentTable || !childTable) return '';

  const parentColumns = reference.joins
    .map((join) => {
      const parentColumn = parentTable.columns.find(
        (column) => column.id === join.parentColumn || column.code === join.parentColumn || column.name === join.parentColumn,
      );
      return parentColumn ? escapeIdentifier(parentColumn.name) : '';
    })
    .filter(Boolean);

  const childColumns = reference.joins
    .map((join) => {
      const childColumn = childTable.columns.find(
        (column) => column.id === join.childColumn || column.code === join.childColumn || column.name === join.childColumn,
      );
      return childColumn ? escapeIdentifier(childColumn.name) : '';
    })
    .filter(Boolean);

  if (parentColumns.length === 0 || childColumns.length === 0) return '';

  return `ALTER TABLE ${escapeIdentifier(childTable.name)} ADD CONSTRAINT ${escapeIdentifier(reference.name)} FOREIGN KEY (${childColumns.join(', ')}) REFERENCES ${escapeIdentifier(parentTable.name)} (${parentColumns.join(', ')});`;
}

export function generateModelSql(model: Pick<Model, 'tables' | 'references'>): string {
  const tablesById = new Map(model.tables.map((table) => [table.id, table]));

  const tableScripts = model.tables.map((table) => generateTableSql(table)).join('\n\n');
  const referenceScripts = model.references
    .map((reference) => generateReferenceSql(reference, tablesById))
    .filter(Boolean)
    .join('\n\n');

  const parts = [tableScripts];
  if (referenceScripts) parts.push(referenceScripts);

  return parts.join('\n\n');
}
