import { describe, expect, it } from 'vitest';
import { generateTableSql } from './sqlGenerator';

describe('generateTableSql', () => {
  it('builds Oracle-style CREATE TABLE and index statements from a model table', () => {
    const table = {
      id: 'table-1',
      code: 'Customer',
      name: 'Customer',
      comment: 'Clientes',
      columns: [
        { id: 'column-1', code: 'CustomerID', name: 'CustomerID', dataType: 'INTEGER', mandatory: true, identity: true },
        { id: 'column-2', code: 'Email', name: 'Email', dataType: 'VARCHAR', mandatory: false, identity: false, length: 200 },
      ],
      primaryKey: ['column-1'],
      keys: [{ id: 'key-1', name: 'PK_Customer', columns: ['column-1'], isPrimary: true }],
      indexes: [{ id: 'index-1', name: 'IX_Customer_Email', columns: ['column-2'], unique: false }],
    };

    const sql = generateTableSql(table);

    expect(sql).toContain('CREATE TABLE "Customer"');
    expect(sql).toContain('"CustomerID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(sql).toContain('CONSTRAINT "PK_Customer" PRIMARY KEY ("CustomerID")');
    expect(sql).toContain('CREATE INDEX "IX_Customer_Email"');
    expect(sql).toContain('ON "Customer" ("Email")');
  });
});
